### ISSUE TITLE
Change icon and name so users dont confuse with OctoPi

### ISSUE THREAD

**Issue by guysoft** [guysoft/OctoKlipperPi#4]
Following a talk with @foosel it seems some users are downloading OctoPi-Klipper thinking its plain OctoPi and then complaining that the OctoKlipper plugin is confusing them and nothing works right.

Although this means klipper so easy to install OctoPi (finally). It does confuse come users because its too easy and too similar.

This means that either we make it visually different from OctoPi in the rpi-imager list, aka change name and logo.
Or I am open to any other ideas.

**Comment by guysoft** [comment]
Other Ideas - OctoKlipperOS OctoKlipperPI. I think OctoKlipperOS looks the most different.

**Comment by foosel** [comment]
Not very different from future plans however, so I'm rather voting for OctoKlipperPi ;)

**Comment by guysoft** [comment]
![Screenshot_20220310_234512](https://user-images.githubusercontent.com/325670/157759985-b62d9b5e-acb8-4f17-a485-caf768aa7348.png)
Tada!... closing

I hope people find it though.
